require:
  - rubocop-rails
  - rubocop-performance
  - rubocop-rspec

AllCops:
  Exclude:
    - db/migrate/*.rb
    - bin/*
    - config/application.rb
    - 'config/initializers/**/*.rb'
    - "**/vendor/**/*"
    - 'vendor/**/*'
    - app/rpc/proto/*
    - 'db/schema.rb'
    - 'node_modules/**/*'
    - 'public/**/*'
    - 'tmp/**/*'
    - 'log/**/*'
    - 'storage/**/*'
  NewCops: enable
  TargetRubyVersion: 3.0

# We use class vars and will have to continue doing so for compatability
Style/ClassVars:
  Enabled: false

# We need these names for backwards compatability
Naming/PredicateName:
  Enabled: false

# We want to name rescued errors as error not simply e.
Naming/RescuedExceptionsVariableName:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

# This has been used for customization
Style/MutableConstant:
  Enabled: false

Style/EmptyElse:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/Next:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/WordArray:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false

Performance/Count:
  Enabled: true

Style/RaiseArgs:
  Enabled: false

Naming/BinaryOperatorParameterName:
  Enabled: false

# We can use good judgement here
Style/RegexpLiteral:
  Enabled: false

# Unicode comments are useful
Style/AsciiComments:
  Enabled: false

Layout/EndAlignment:
  Enabled: true

Layout/ElseAlignment:
  Enabled: true

Layout/IndentationWidth:
  Enabled: true

Layout/ParameterAlignment:
  Enabled: true

Layout/ClosingParenthesisIndentation:
  Enabled: true

Layout/MultilineMethodCallIndentation:
  Enabled: true

Layout/FirstArrayElementIndentation:
  Enabled: true

Layout/FirstHashElementIndentation:
  Enabled: true

Layout/HashAlignment:
  Enabled: true

Style/TrailingCommaInArguments:
  Enabled: true

Style/TrailingCommaInArrayLiteral:
  Enabled: true

Style/TrailingCommaInHashLiteral:
  Enabled: true

Rails/HelperInstanceVariable:
  Enabled: false

# Symbol Arrays are ok and the %i syntax widely unknown
Style/SymbolArray:
  Enabled: true

Rails/DynamicFindBy:
  Whitelist:
    - find_by_param
    - find_by_param!

# It's okay to skip model validations to setup a spec.
Rails/SkipsModelValidations:
  Exclude:
    - db/seeds/**/*.rb
    - "*/spec/**/*"

# We use a lot of
#
#     expect {
#       something
#     }.to { happen }
#
# syntax in the specs files.
Lint/AmbiguousBlockAssociation:
  Exclude:
    - "*/spec/**/*"
    - "spec/**/*" # For the benefit of apps that inherit from this config

Security/Eval:
  Exclude:
    - "Gemfile"
    - "*/Gemfile"

Naming/VariableNumber:
  Enabled: false

# Write empty methods as you wish.
Style/EmptyMethod:
  Enabled: false

# From http://relaxed.ruby.style/

Style/Alias:
  Enabled: false
  StyleGuide: http://relaxed.ruby.style/#stylealias

Style/BeginBlock:
  Enabled: false
  StyleGuide: http://relaxed.ruby.style/#stylebeginblock

Style/BlockDelimiters:
  Enabled: false
  StyleGuide: http://relaxed.ruby.style/#styleblockdelimiters

Style/Documentation:
  Enabled: false
  StyleGuide: http://relaxed.ruby.style/#styledocumentation

Layout/DotPosition:
  Enabled: false
  StyleGuide: http://relaxed.ruby.style/#styledotposition

Style/DoubleNegation:
  Enabled: false
  StyleGuide: http://relaxed.ruby.style/#styledoublenegation

Style/EndBlock:
  Enabled: false
  StyleGuide: http://relaxed.ruby.style/#styleendblock

Style/FormatString:
  Enabled: false
  StyleGuide: http://relaxed.ruby.style/#styleformatstring

Style/IfUnlessModifier:
  Enabled: false
  StyleGuide: http://relaxed.ruby.style/#styleifunlessmodifier

Style/Lambda:
  Enabled: false
  StyleGuide: http://relaxed.ruby.style/#stylelambda

Style/ModuleFunction:
  Enabled: false
  StyleGuide: http://relaxed.ruby.style/#stylemodulefunction

Style/MultilineBlockChain:
  Enabled: false
  StyleGuide: http://relaxed.ruby.style/#stylemultilineblockchain

Style/NegatedIf:
  Enabled: false
  StyleGuide: http://relaxed.ruby.style/#stylenegatedif

Style/NegatedWhile:
  Enabled: false
  StyleGuide: http://relaxed.ruby.style/#stylenegatedwhile

Style/ParallelAssignment:
  Enabled: false
  StyleGuide: http://relaxed.ruby.style/#styleparallelassignment

Style/PercentLiteralDelimiters:
  Enabled: false
  StyleGuide: http://relaxed.ruby.style/#stylepercentliteraldelimiters

Style/PerlBackrefs:
  Enabled: false
  StyleGuide: http://relaxed.ruby.style/#styleperlbackrefs

Style/Semicolon:
  Enabled: false
  StyleGuide: http://relaxed.ruby.style/#stylesemicolon

Style/SignalException:
  Enabled: false
  StyleGuide: http://relaxed.ruby.style/#stylesignalexception

Style/SingleLineBlockParams:
  Enabled: false
  StyleGuide: http://relaxed.ruby.style/#stylesinglelineblockparams

Style/SingleLineMethods:
  Enabled: false
  StyleGuide: http://relaxed.ruby.style/#stylesinglelinemethods

Layout/SpaceBeforeBlockBraces:
  Enabled: false
  StyleGuide: http://relaxed.ruby.style/#stylespacebeforeblockbraces

Layout/SpaceInsideParens:
  Enabled: false
  StyleGuide: http://relaxed.ruby.style/#stylespaceinsideparens

Style/SpecialGlobalVars:
  Enabled: true
  StyleGuide: http://relaxed.ruby.style/#stylespecialglobalvars

Style/StringLiterals:
  Enabled: false
  StyleGuide: http://relaxed.ruby.style/#stylestringliterals

Style/SymbolProc:
  Enabled: false

Style/TernaryParentheses:
  Enabled: false

Style/WhileUntilModifier:
  Enabled: false
  StyleGuide: http://relaxed.ruby.style/#stylewhileuntilmodifier

Lint/AmbiguousRegexpLiteral:
  Enabled: false
  StyleGuide: http://relaxed.ruby.style/#lintambiguousregexpliteral

Lint/AssignmentInCondition:
  Enabled: false
  StyleGuide: http://relaxed.ruby.style/#lintassignmentincondition

Metrics/AbcSize:
  Enabled: false

Metrics/BlockNesting:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Layout/LineLength:
  Enabled: true

Metrics/MethodLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always

Style/FetchEnvVar:
  Enabled: true

# json.() is idiomatic in jbuilder files
Style/LambdaCall:
  Enabled: false

Naming/MethodParameterName:
  AllowedNames:
    - id
    - to
    - _

# Rubocop doesn't understand side-effects
Style/IdenticalConditionalBranches:
  Enabled: false

Naming/MemoizedInstanceVariableName:
  Enabled: true

Lint/BinaryOperatorWithIdenticalOperands:
  Enabled: false

Lint/SuppressedException:
  Enabled: false

Rails/ReflectionClassName:
  Enabled: true
  Exclude:
    - app/models/ibrain/role_user.rb

Gemspec/DeprecatedAttributeAssignment:
  Enabled: true

Gemspec/RequireMFA:
  Enabled: true

Layout/LineEndStringConcatenationIndentation:
  Enabled: true

Layout/SpaceBeforeBrackets:
  Enabled: true

Lint/AmbiguousAssignment:
  Enabled: true

Lint/AmbiguousOperatorPrecedence:
  Enabled: true

Lint/AmbiguousRange:
  Enabled: true

Lint/DeprecatedConstants:
  Enabled: true

Lint/DuplicateBranch:
  Enabled: true

Lint/DuplicateRegexpCharacterClassElement:
  Enabled: true

Lint/EmptyBlock:
  Enabled: true

Lint/EmptyClass:
  Enabled: true

Lint/EmptyInPattern:
  Enabled: true

Lint/IncompatibleIoSelectWithFiberScheduler:
  Enabled: true

Lint/LambdaWithoutLiteralBlock:
  Enabled: true

Lint/NoReturnInBeginEndBlocks:
  Enabled: true

Lint/NumberedParameterAssignment:
  Enabled: true

Lint/OrAssignmentToConstant:
  Enabled: true

Lint/RedundantDirGlobSort:
  Enabled: true

Lint/RequireRelativeSelfPath:
  Enabled: true

Lint/SymbolConversion:
  Enabled: true

Lint/ToEnumArguments:
  Enabled: true

Lint/TripleQuotes:
  Enabled: true

Lint/UnexpectedBlockArity:
  Enabled: true

Lint/UnmodifiedReduceAccumulator:
  Enabled: true

Lint/UselessRuby2Keywords:
  Enabled: true

Security/IoMethods:
  Enabled: true

Style/ArgumentsForwarding:
  Enabled: true

Style/CollectionCompact:
  Enabled: true

Style/DocumentDynamicEvalDefinition:
  Enabled: true

Style/EndlessMethod:
  Enabled: true

Style/HashConversion:
  Enabled: true

Style/HashExcept:
  Enabled: true

Style/IfWithBooleanLiteralBranches:
  Enabled: true

Style/InPatternThen:
  Enabled: true

Style/MultilineInPatternThen:
  Enabled: true

Style/NegatedIfElseCondition:
  Enabled: true

Style/NilLambda:
  Enabled: true

Style/NumberedParameters:
  Enabled: true

Style/NumberedParametersLimit:
  Enabled: true

Style/OpenStructUse:
  Enabled: true

Style/QuotedSymbols:
  Enabled: true

Style/RedundantArgument:
  Enabled: true

Style/RedundantSelfAssignmentBranch:
  Enabled: true

Style/SelectByRegexp:
  Enabled: true

Style/StringChars:
  Enabled: true

Style/SwapValues:
  Enabled: true

Performance/AncestorsInclude:
  Enabled: true

Performance/BigDecimalWithNumericArgument:
  Enabled: true

Performance/BlockGivenWithExplicitBlock:
  Enabled: true

Performance/CollectionLiteralInLoop:
  Enabled: true

Performance/ConcurrentMonotonicTime:
  Enabled: true

Performance/ConstantRegexp:
  Enabled: true

Performance/MapCompact:
  Enabled: true

Performance/MethodObjectAsBlock:
  Enabled: true

Performance/RedundantEqualityComparisonBlock:
  Enabled: true

Performance/RedundantSortBlock:
  Enabled: true

Performance/RedundantSplitRegexpArgument:
  Enabled: true

Performance/RedundantStringChars:
  Enabled: true

Performance/ReverseFirst:
  Enabled: true

Performance/SortReverse:
  Enabled: true

Performance/Squeeze:
  Enabled: true

Performance/StringInclude:
  Enabled: true

Performance/Sum:
  Enabled: true

Rails/ActiveRecordCallbacksOrder:
  Enabled: true

Rails/AddColumnIndex:
  Enabled: true

Rails/AfterCommitOverride:
  Enabled: true

Rails/AttributeDefaultBlockValue:
  Enabled: true

Rails/EagerEvaluationLogMessage:
  Enabled: true

Rails/ExpandedDateRange:
  Enabled: true

Rails/FindById:
  Enabled: true

Rails/I18nLocaleAssignment:
  Enabled: true

Rails/Inquiry:
  Enabled: true

Rails/MailerName:
  Enabled: true

Rails/MatchRoute:
  Enabled: true

Rails/NegateInclude:
  Enabled: true

Rails/Pluck:
  Enabled: true

Rails/PluckInWhere:
  Enabled: true

Rails/RedundantTravelBack:
  Enabled: true

Rails/RenderInline:
  Enabled: true

Rails/RenderPlainText:
  Enabled: true

Rails/ShortI18n:
  Enabled: true

Rails/SquishedSQLHeredocs:
  Enabled: true

Rails/TimeZoneAssignment:
  Enabled: true

Rails/UnusedIgnoredColumns:
  Enabled: true

Rails/WhereEquals:
  Enabled: true

Rails/WhereExists:
  Enabled: true

Rails/WhereNot:
  Enabled: true

Gemspec/RequiredRubyVersion:
  Enabled: false

Rails/UnknownEnv:
  Environments:
    - production
    - development
    - test
    - staging

Style/MixinUsage:
  Enabled: true
  Exclude:
    - db/seeds/*.rb

Style/AccessorGrouping:
  Enabled: true

Layout/AccessModifierIndentation:
  Enabled: true
  EnforcedStyle: indent

Layout/ArrayAlignment:
  Enabled: true

Layout/ArgumentAlignment:
  Enabled: true

Layout/ClassStructure:
  Categories:
    association:
      - has_many
      - has_one
    attribute_macros:
      - attr_accessor
      - attr_reader
      - attr_writer
    macros:
      - validates
      - validate
    module_inclusion:
      - include
      - prepend
      - extend

Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods

Layout/InitialIndentation:
  Enabled: true

Layout/IndentationStyle:
  EnforcedStyle: spaces

Style/ClassAndModuleChildren:
  EnforcedStyle: compact
