default: &default
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_bin
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: <%= ENV.fetch('DATABASE_USERNAME') { '' } %>
  password: <%= ENV.fetch('DATABASE_PASSWORD') { '' } %>
  host: <%= ENV.fetch('MYSQL_HOSTNAME') { 'localhost' } %>

development:
  <<: *default
  database: share_video_development

test:
  <<: *default
  database: share_video_test

production:
  <<: *default
  database: <%= ENV.fetch('DATABASE_URL') { 'share_video_production' } %>
